version: "3"
services:

  gateway:
    image: nginx:1.25-bookworm
    volumes:
      - ./gateway_nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8000:80"
    depends_on:
      - order-service
      - stock-service
      - payment-service

  order-service:
    build: ./order
    image: order:latest
    environment:
      - GATEWAY_URL=http://gateway:80
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/order_redis.env
    depends_on:
      - redis-sentinel-order

  redis-master-order:
    image: redis:7.2-bookworm
    container_name: redis-master-order
    ports:
      - "6379:6379"
    volumes:
      - ./master/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

  redis-replica1-order:
    image: redis:7.2-bookworm
    container_name: redis-replica1-order
    depends_on:
      - redis-master-order
    command: ["redis-server", "--slaveof", "redis-master-order", "6379", "--masterauth", "redis", "--requirepass", "redis"]

  redis-replica2-order:
    image: redis:7.2-bookworm
    container_name: redis-replica2-order
    depends_on:
      - redis-master-order
    command: ["redis-server", "--slaveof", "redis-master-order", "6379", "--masterauth", "redis", "--requirepass", "redis"]

  redis-sentinel-order:
    image: redis:7.2-bookworm
    container_name: redis-sentinel-order
    depends_on:
      - redis-master-order
      - redis-replica1-order
      - redis-replica2-order
    ports:
      - "26379:26379"
    command:
      - sh
      - -lc
      - |
        set -eu
        mkdir -p /etc/redis
        printf "%s\n" \
          "bind 0.0.0.0" \
          "protected-mode no" \
          "port 26379" \
          "sentinel resolve-hostnames yes" \
          "sentinel announce-hostnames yes" \
          "sentinel monitor order-master redis-master-order 6379 1" \
          "sentinel auth-pass order-master redis" \
          "sentinel down-after-milliseconds order-master 800" \
          "sentinel failover-timeout order-master 2000" \
          > /etc/redis/sentinel.conf
        exec redis-sentinel /etc/redis/sentinel.conf


  stock-service:
    build: ./stock
    image: stock:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/stock_redis.env
    depends_on:
      - stock-db

  stock-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb

  payment-service:
    build: ./payment
    image: user:latest
    command: gunicorn -b 0.0.0.0:5000 -w 2 --timeout 30 --log-level=info app:app
    env_file:
      - env/payment_redis.env
    depends_on:
      - payment-db

  payment-db:
    image: redis:7.2-bookworm
    command: redis-server --requirepass redis --maxmemory 512mb
