bind 0.0.0.0
protected-mode no
port 26379
dir /data
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor order-master redis-master-order 6379 1
sentinel auth-pass order-master redis
sentinel down-after-milliseconds order-master 2400
sentinel failover-timeout order-master 2000
