bind 0.0.0.0
protected-mode no
port 26379
dir /data
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor stock-master redis-master-stock 6379 1
sentinel auth-pass stock-master redis
sentinel down-after-milliseconds stock-master 2400
sentinel failover-timeout stock-master 2000
